version: "3"
services:
  nginx:
    image: nginx
    ports:
    - "5001:80"
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/log:/var/log/nginx
    depends_on:
    - python
  python:
    build: .
    volumes:
    - ./flask:/app
    depends_on:
    - mysql
    environment:
      FLASK_ENV: development
    command: flask run --host=0.0.0.0
  mysql:
    image: mysql
    volumes:
    - ./database:/var/lib/mysql
    ports:
    - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
